// Auto-generated curated item pool
// This file contains 355 carefully selected items for flipping analysis

export interface ItemPoolEntry {
  id: number;
  name: string;
  category: 'runes' | 'ammo' | 'potions' | 'herbs' | 'resources' | 'bones' | 'food' | 'armor' | 'weapons' | 'jewelry' | 'shields' | 'upgrades' | 'other';
  tier: 'high' | 'medium' | 'low';
}

export const EXPANDED_ITEM_POOL: ItemPoolEntry[] = [
  { id: 556, name: "Air rune", category: "runes", tier: "low" },
  { id: 555, name: "Water rune", category: "runes", tier: "low" },
  { id: 557, name: "Earth rune", category: "runes", tier: "low" },
  { id: 554, name: "Fire rune", category: "runes", tier: "low" },
  { id: 558, name: "Mind rune", category: "runes", tier: "low" },
  { id: 559, name: "Body rune", category: "runes", tier: "low" },
  { id: 562, name: "Chaos rune", category: "runes", tier: "low" },
  { id: 564, name: "Cosmic rune", category: "runes", tier: "low" },
  { id: 561, name: "Nature rune", category: "runes", tier: "low" },
  { id: 563, name: "Law rune", category: "runes", tier: "low" },
  { id: 560, name: "Death rune", category: "runes", tier: "low" },
  { id: 565, name: "Blood rune", category: "runes", tier: "low" },
  { id: 566, name: "Soul rune", category: "runes", tier: "low" },
  { id: 21880, name: "Wrath rune", category: "runes", tier: "low" },
  { id: 9075, name: "Astral rune", category: "runes", tier: "low" },
  { id: 4695, name: "Mist rune", category: "runes", tier: "low" },
  { id: 4696, name: "Dust rune", category: "runes", tier: "low" },
  { id: 4697, name: "Smoke rune", category: "runes", tier: "low" },
  { id: 4694, name: "Steam rune", category: "runes", tier: "low" },
  { id: 4699, name: "Lava rune", category: "runes", tier: "low" },
  { id: 4698, name: "Mud rune", category: "runes", tier: "low" },
  { id: 314, name: "Feather", category: "other", tier: "low" },
  { id: 52, name: "Arrow shaft", category: "ammo", tier: "low" },
  { id: 53, name: "Headless arrow", category: "ammo", tier: "low" },
  { id: 11875, name: "Broad bolts", category: "ammo", tier: "low" },
  { id: 21316, name: "Amethyst broad bolts", category: "ammo", tier: "low" },
  { id: 9143, name: "Adamant bolts", category: "ammo", tier: "low" },
  { id: 9144, name: "Runite bolts", category: "ammo", tier: "low" },
  { id: 9144, name: "Runite bolts", category: "ammo", tier: "low" },
  { id: 21905, name: "Dragon bolts", category: "ammo", tier: "medium" },
  { id: 21930, name: "Dragon bolts (unf)", category: "ammo", tier: "medium" },
  { id: 9242, name: "Ruby bolts (e)", category: "ammo", tier: "low" },
  { id: 9243, name: "Diamond bolts (e)", category: "ammo", tier: "low" },
  { id: 9241, name: "Emerald bolts (e)", category: "ammo", tier: "low" },
  { id: 9240, name: "Sapphire bolts (e)", category: "ammo", tier: "low" },
  { id: 21944, name: "Ruby dragon bolts (e)", category: "ammo", tier: "medium" },
  { id: 21946, name: "Diamond dragon bolts (e)", category: "ammo", tier: "medium" },
  { id: 21948, name: "Dragonstone dragon bolts (e)", category: "ammo", tier: "medium" },
  { id: 21950, name: "Onyx dragon bolts (e)", category: "ammo", tier: "medium" },
  { id: 11212, name: "Dragon arrow", category: "ammo", tier: "medium" },
  { id: 11237, name: "Dragon arrowtips", category: "ammo", tier: "medium" },
  { id: 21326, name: "Amethyst arrow", category: "ammo", tier: "low" },
  { id: 21350, name: "Amethyst arrowtips", category: "ammo", tier: "low" },
  { id: 892, name: "Rune arrow", category: "runes", tier: "low" },
  { id: 44, name: "Rune arrowtips", category: "runes", tier: "low" },
  { id: 11230, name: "Dragon dart", category: "ammo", tier: "medium" },
  { id: 11232, name: "Dragon dart tip", category: "ammo", tier: "medium" },
  { id: 25849, name: "Amethyst dart", category: "ammo", tier: "low" },
  { id: 25853, name: "Amethyst dart tip", category: "ammo", tier: "low" },
  { id: 811, name: "Rune dart", category: "runes", tier: "low" },
  { id: 824, name: "Rune dart tip", category: "runes", tier: "low" },
  { id: 10033, name: "Chinchompa", category: "ammo", tier: "low" },
  { id: 10034, name: "Red chinchompa", category: "ammo", tier: "low" },
  { id: 11959, name: "Black chinchompa", category: "ammo", tier: "low" },
  { id: 1511, name: "Logs", category: "resources", tier: "low" },
  { id: 1521, name: "Oak logs", category: "resources", tier: "low" },
  { id: 1519, name: "Willow logs", category: "resources", tier: "low" },
  { id: 1517, name: "Maple logs", category: "resources", tier: "low" },
  { id: 1515, name: "Yew logs", category: "resources", tier: "low" },
  { id: 1513, name: "Magic logs", category: "resources", tier: "low" },
  { id: 6333, name: "Teak logs", category: "resources", tier: "low" },
  { id: 6332, name: "Mahogany logs", category: "resources", tier: "low" },
  { id: 10810, name: "Arctic pine logs", category: "resources", tier: "low" },
  { id: 1779, name: "Flax", category: "resources", tier: "low" },
  { id: 31045, name: "Bale of flax", category: "resources", tier: "low" },
  { id: 1777, name: "Bow string", category: "resources", tier: "low" },
  { id: 54, name: "Oak shortbow (u)", category: "weapons", tier: "low" },
  { id: 60, name: "Willow shortbow (u)", category: "weapons", tier: "low" },
  { id: 64, name: "Maple shortbow (u)", category: "weapons", tier: "low" },
  { id: 68, name: "Yew shortbow (u)", category: "weapons", tier: "low" },
  { id: 72, name: "Magic shortbow (u)", category: "weapons", tier: "low" },
  { id: 56, name: "Oak longbow (u)", category: "weapons", tier: "low" },
  { id: 58, name: "Willow longbow (u)", category: "weapons", tier: "low" },
  { id: 62, name: "Maple longbow (u)", category: "weapons", tier: "low" },
  { id: 66, name: "Yew longbow (u)", category: "weapons", tier: "low" },
  { id: 70, name: "Magic longbow (u)", category: "weapons", tier: "low" },
  { id: 851, name: "Maple longbow", category: "weapons", tier: "low" },
  { id: 855, name: "Yew longbow", category: "weapons", tier: "low" },
  { id: 859, name: "Magic longbow", category: "weapons", tier: "low" },
  { id: 853, name: "Maple shortbow", category: "weapons", tier: "low" },
  { id: 857, name: "Yew shortbow", category: "weapons", tier: "low" },
  { id: 861, name: "Magic shortbow", category: "weapons", tier: "low" },
  { id: 436, name: "Copper ore", category: "resources", tier: "low" },
  { id: 438, name: "Tin ore", category: "resources", tier: "low" },
  { id: 440, name: "Iron ore", category: "resources", tier: "low" },
  { id: 442, name: "Silver ore", category: "resources", tier: "low" },
  { id: 444, name: "Gold ore", category: "resources", tier: "low" },
  { id: 453, name: "Coal", category: "other", tier: "low" },
  { id: 447, name: "Mithril ore", category: "resources", tier: "low" },
  { id: 449, name: "Adamantite ore", category: "resources", tier: "low" },
  { id: 451, name: "Runite ore", category: "resources", tier: "low" },
  { id: 2349, name: "Bronze bar", category: "resources", tier: "low" },
  { id: 2351, name: "Iron bar", category: "resources", tier: "low" },
  { id: 2353, name: "Steel bar", category: "resources", tier: "low" },
  { id: 2355, name: "Silver bar", category: "resources", tier: "low" },
  { id: 2357, name: "Gold bar", category: "resources", tier: "low" },
  { id: 2359, name: "Mithril bar", category: "resources", tier: "low" },
  { id: 2361, name: "Adamantite bar", category: "resources", tier: "low" },
  { id: 2363, name: "Runite bar", category: "resources", tier: "low" },
  { id: 1539, name: "Steel nails", category: "resources", tier: "low" },
  { id: 4822, name: "Mithril nails", category: "resources", tier: "low" },
  { id: 4823, name: "Adamantite nails", category: "resources", tier: "low" },
  { id: 4824, name: "Rune nails", category: "runes", tier: "low" },
  { id: 960, name: "Plank", category: "resources", tier: "low" },
  { id: 8778, name: "Oak plank", category: "resources", tier: "low" },
  { id: 8780, name: "Teak plank", category: "resources", tier: "low" },
  { id: 8782, name: "Mahogany plank", category: "resources", tier: "low" },
  { id: 1783, name: "Bucket of sand", category: "resources", tier: "low" },
  { id: 6971, name: "Sandstone (1kg)", category: "resources", tier: "low" },
  { id: 1781, name: "Soda ash", category: "resources", tier: "low" },
  { id: 401, name: "Seaweed", category: "resources", tier: "low" },
  { id: 21504, name: "Giant seaweed", category: "resources", tier: "low" },
  { id: 1775, name: "Molten glass", category: "resources", tier: "low" },
  { id: 1741, name: "Leather", category: "resources", tier: "low" },
  { id: 1743, name: "Hard leather", category: "resources", tier: "low" },
  { id: 1739, name: "Cowhide", category: "resources", tier: "low" },
  { id: 1753, name: "Green dragonhide", category: "resources", tier: "medium" },
  { id: 1751, name: "Blue dragonhide", category: "resources", tier: "medium" },
  { id: 1749, name: "Red dragonhide", category: "resources", tier: "medium" },
  { id: 1747, name: "Black dragonhide", category: "resources", tier: "medium" },
  { id: 1745, name: "Green dragon leather", category: "resources", tier: "medium" },
  { id: 2505, name: "Blue dragon leather", category: "resources", tier: "medium" },
  { id: 2507, name: "Red dragon leather", category: "resources", tier: "medium" },
  { id: 2509, name: "Black dragon leather", category: "resources", tier: "medium" },
  { id: 526, name: "Bones", category: "bones", tier: "low" },
  { id: 532, name: "Big bones", category: "bones", tier: "low" },
  { id: 536, name: "Dragon bones", category: "bones", tier: "medium" },
  { id: 534, name: "Babydragon bones", category: "bones", tier: "medium" },
  { id: 6812, name: "Wyvern bones", category: "bones", tier: "low" },
  { id: 22124, name: "Superior dragon bones", category: "bones", tier: "medium" },
  { id: 21975, name: "Crushed superior dragon bones", category: "bones", tier: "medium" },
  { id: 3142, name: "Raw karambwan", category: "food", tier: "low" },
  { id: 3144, name: "Cooked karambwan", category: "food", tier: "low" },
  { id: 3144, name: "Cooked karambwan", category: "food", tier: "low" },
  { id: 383, name: "Raw shark", category: "food", tier: "low" },
  { id: 385, name: "Shark", category: "food", tier: "low" },
  { id: 389, name: "Raw manta ray", category: "food", tier: "low" },
  { id: 391, name: "Manta ray", category: "food", tier: "low" },
  { id: 13439, name: "Raw anglerfish", category: "food", tier: "low" },
  { id: 13441, name: "Anglerfish", category: "food", tier: "low" },
  { id: 7944, name: "Raw monkfish", category: "food", tier: "low" },
  { id: 7946, name: "Monkfish", category: "food", tier: "low" },
  { id: 11936, name: "Dark crab", category: "food", tier: "low" },
  { id: 379, name: "Lobster", category: "food", tier: "low" },
  { id: 377, name: "Raw lobster", category: "food", tier: "low" },
  { id: 2434, name: "Prayer potion(4)", category: "potions", tier: "low" },
  { id: 3024, name: "Super restore(4)", category: "resources", tier: "low" },
  { id: 6685, name: "Saradomin brew(4)", category: "potions", tier: "low" },
  { id: 12625, name: "Stamina potion(4)", category: "potions", tier: "low" },
  { id: 12695, name: "Super combat potion(4)", category: "potions", tier: "low" },
  { id: 2444, name: "Ranging potion(4)", category: "potions", tier: "low" },
  { id: 22461, name: "Bastion potion(4)", category: "potions", tier: "low" },
  { id: 3040, name: "Magic potion(4)", category: "potions", tier: "low" },
  { id: 21978, name: "Super antifire potion(4)", category: "potions", tier: "low" },
  { id: 22209, name: "Extended super antifire(4)", category: "potions", tier: "low" },
  { id: 2450, name: "Zamorak brew(4)", category: "potions", tier: "low" },
  { id: 23685, name: "Divine super combat potion(4)", category: "potions", tier: "low" },
  { id: 23733, name: "Divine ranging potion(4)", category: "potions", tier: "low" },
  { id: 24635, name: "Divine bastion potion(4)", category: "potions", tier: "low" },
  { id: 24592, name: "Blighted anglerfish", category: "food", tier: "low" },
  { id: 24589, name: "Blighted manta ray", category: "food", tier: "low" },
  { id: 24595, name: "Blighted karambwan", category: "food", tier: "low" },
  { id: 24598, name: "Blighted super restore(4)", category: "resources", tier: "low" },
  { id: 6685, name: "Saradomin brew(4)", category: "potions", tier: "low" },
  { id: 12695, name: "Super combat potion(4)", category: "potions", tier: "low" },
  { id: 2434, name: "Prayer potion(4)", category: "potions", tier: "low" },
  { id: 227, name: "Vial of water", category: "other", tier: "low" },
  { id: 229, name: "Vial", category: "other", tier: "low" },
  { id: 199, name: "Grimy guam leaf", category: "herbs", tier: "low" },
  { id: 201, name: "Grimy marrentill", category: "herbs", tier: "low" },
  { id: 203, name: "Grimy tarromin", category: "herbs", tier: "low" },
  { id: 205, name: "Grimy harralander", category: "herbs", tier: "low" },
  { id: 207, name: "Grimy ranarr weed", category: "herbs", tier: "low" },
  { id: 3049, name: "Grimy toadflax", category: "herbs", tier: "low" },
  { id: 209, name: "Grimy irit leaf", category: "herbs", tier: "low" },
  { id: 211, name: "Grimy avantoe", category: "herbs", tier: "low" },
  { id: 213, name: "Grimy kwuarm", category: "herbs", tier: "low" },
  { id: 3051, name: "Grimy snapdragon", category: "herbs", tier: "medium" },
  { id: 215, name: "Grimy cadantine", category: "herbs", tier: "low" },
  { id: 2485, name: "Grimy lantadyme", category: "herbs", tier: "low" },
  { id: 217, name: "Grimy dwarf weed", category: "herbs", tier: "low" },
  { id: 219, name: "Grimy torstol", category: "herbs", tier: "low" },
  { id: 249, name: "Guam leaf", category: "herbs", tier: "low" },
  { id: 251, name: "Marrentill", category: "herbs", tier: "low" },
  { id: 253, name: "Tarromin", category: "herbs", tier: "low" },
  { id: 255, name: "Harralander", category: "herbs", tier: "low" },
  { id: 257, name: "Ranarr weed", category: "herbs", tier: "low" },
  { id: 2998, name: "Toadflax", category: "herbs", tier: "low" },
  { id: 259, name: "Irit leaf", category: "herbs", tier: "low" },
  { id: 261, name: "Avantoe", category: "herbs", tier: "low" },
  { id: 263, name: "Kwuarm", category: "herbs", tier: "low" },
  { id: 3000, name: "Snapdragon", category: "herbs", tier: "medium" },
  { id: 265, name: "Cadantine", category: "herbs", tier: "low" },
  { id: 2481, name: "Lantadyme", category: "herbs", tier: "low" },
  { id: 267, name: "Dwarf weed", category: "herbs", tier: "low" },
  { id: 269, name: "Torstol", category: "herbs", tier: "low" },
  { id: 5291, name: "Guam seed", category: "herbs", tier: "low" },
  { id: 5292, name: "Marrentill seed", category: "herbs", tier: "low" },
  { id: 5293, name: "Tarromin seed", category: "herbs", tier: "low" },
  { id: 5294, name: "Harralander seed", category: "herbs", tier: "low" },
  { id: 5295, name: "Ranarr seed", category: "herbs", tier: "low" },
  { id: 5296, name: "Toadflax seed", category: "herbs", tier: "low" },
  { id: 5297, name: "Irit seed", category: "herbs", tier: "low" },
  { id: 5298, name: "Avantoe seed", category: "herbs", tier: "low" },
  { id: 5299, name: "Kwuarm seed", category: "herbs", tier: "low" },
  { id: 5300, name: "Snapdragon seed", category: "herbs", tier: "medium" },
  { id: 5301, name: "Cadantine seed", category: "herbs", tier: "low" },
  { id: 5302, name: "Lantadyme seed", category: "herbs", tier: "low" },
  { id: 5303, name: "Dwarf weed seed", category: "herbs", tier: "low" },
  { id: 5304, name: "Torstol seed", category: "herbs", tier: "low" },
  { id: 91, name: "Guam potion (unf)", category: "potions", tier: "low" },
  { id: 93, name: "Marrentill potion (unf)", category: "potions", tier: "low" },
  { id: 95, name: "Tarromin potion (unf)", category: "potions", tier: "low" },
  { id: 97, name: "Harralander potion (unf)", category: "potions", tier: "low" },
  { id: 99, name: "Ranarr potion (unf)", category: "potions", tier: "low" },
  { id: 3002, name: "Toadflax potion (unf)", category: "potions", tier: "low" },
  { id: 101, name: "Irit potion (unf)", category: "potions", tier: "low" },
  { id: 103, name: "Avantoe potion (unf)", category: "potions", tier: "low" },
  { id: 105, name: "Kwuarm potion (unf)", category: "potions", tier: "low" },
  { id: 3004, name: "Snapdragon potion (unf)", category: "potions", tier: "medium" },
  { id: 107, name: "Cadantine potion (unf)", category: "potions", tier: "low" },
  { id: 2483, name: "Lantadyme potion (unf)", category: "potions", tier: "low" },
  { id: 109, name: "Dwarf weed potion (unf)", category: "potions", tier: "low" },
  { id: 111, name: "Torstol potion (unf)", category: "potions", tier: "low" },
  { id: 231, name: "Snape grass", category: "other", tier: "low" },
  { id: 225, name: "Limpwurt root", category: "other", tier: "low" },
  { id: 2970, name: "Mort myre fungus", category: "other", tier: "low" },
  { id: 3138, name: "Potato cactus", category: "other", tier: "low" },
  { id: 239, name: "White berries", category: "other", tier: "low" },
  { id: 245, name: "Wine of zamorak", category: "other", tier: "low" },
  { id: 235, name: "Unicorn horn dust", category: "other", tier: "low" },
  { id: 9736, name: "Goat horn dust", category: "other", tier: "low" },
  { id: 1975, name: "Chocolate dust", category: "other", tier: "low" },
  { id: 223, name: "Red spiders' eggs", category: "other", tier: "low" },
  { id: 243, name: "Blue dragon scale", category: "resources", tier: "medium" },
  { id: 221, name: "Eye of newt", category: "other", tier: "low" },
  { id: 6289, name: "Snakeskin", category: "other", tier: "low" },
  { id: 241, name: "Dragon scale dust", category: "resources", tier: "medium" },
  { id: 6693, name: "Crushed nest", category: "other", tier: "low" },
  { id: 6032, name: "Compost", category: "resources", tier: "low" },
  { id: 6034, name: "Supercompost", category: "resources", tier: "low" },
  { id: 21483, name: "Ultracompost", category: "resources", tier: "low" },
  { id: 21622, name: "Volcanic ash", category: "resources", tier: "low" },
  { id: 1391, name: "Battlestaff", category: "weapons", tier: "low" },
  { id: 567, name: "Unpowered orb", category: "resources", tier: "low" },
  { id: 571, name: "Water orb", category: "resources", tier: "low" },
  { id: 575, name: "Earth orb", category: "resources", tier: "low" },
  { id: 569, name: "Fire orb", category: "resources", tier: "low" },
  { id: 573, name: "Air orb", category: "resources", tier: "low" },
  { id: 1395, name: "Water battlestaff", category: "weapons", tier: "low" },
  { id: 1399, name: "Earth battlestaff", category: "weapons", tier: "low" },
  { id: 1393, name: "Fire battlestaff", category: "weapons", tier: "low" },
  { id: 1397, name: "Air battlestaff", category: "weapons", tier: "low" },
  { id: 1623, name: "Uncut sapphire", category: "other", tier: "low" },
  { id: 1621, name: "Uncut emerald", category: "other", tier: "low" },
  { id: 1619, name: "Uncut ruby", category: "other", tier: "low" },
  { id: 1617, name: "Uncut diamond", category: "other", tier: "low" },
  { id: 1631, name: "Uncut dragonstone", category: "other", tier: "medium" },
  { id: 1607, name: "Sapphire", category: "other", tier: "low" },
  { id: 1605, name: "Emerald", category: "other", tier: "low" },
  { id: 1603, name: "Ruby", category: "other", tier: "low" },
  { id: 1601, name: "Diamond", category: "other", tier: "low" },
  { id: 1615, name: "Dragonstone", category: "other", tier: "medium" },
  { id: 4151, name: "Abyssal whip", category: "weapons", tier: "low" },
  { id: 13652, name: "Dragon claws", category: "weapons", tier: "medium" },
  { id: 13576, name: "Dragon warhammer", category: "weapons", tier: "medium" },
  { id: 26219, name: "Osmumten's fang", category: "weapons", tier: "low" },
  { id: 11889, name: "Zamorakian hasta", category: "weapons", tier: "low" },
  { id: 11838, name: "Saradomin sword", category: "weapons", tier: "low" },
  { id: 12934, name: "Zulrah's scales", category: "resources", tier: "low" },
  { id: 11785, name: "Armadyl crossbow", category: "weapons", tier: "medium" },
  { id: 21012, name: "Dragon hunter crossbow", category: "weapons", tier: "medium" },
  { id: 11905, name: "Trident of the seas (full)", category: "weapons", tier: "low" },
  { id: 12002, name: "Occult necklace", category: "jewelry", tier: "medium" },
  { id: 6737, name: "Berserker ring", category: "jewelry", tier: "medium" },
  { id: 6731, name: "Seers ring", category: "jewelry", tier: "medium" },
  { id: 6733, name: "Archers ring", category: "jewelry", tier: "medium" },
  { id: 12601, name: "Ring of the gods", category: "jewelry", tier: "low" },
  { id: 12603, name: "Tyrannical ring", category: "jewelry", tier: "low" },
  { id: 12605, name: "Treasonous ring", category: "jewelry", tier: "low" },
  { id: 11840, name: "Dragon boots", category: "armor", tier: "medium" },
  { id: 13239, name: "Primordial boots", category: "armor", tier: "medium" },
  { id: 13237, name: "Pegasian boots", category: "armor", tier: "medium" },
  { id: 13235, name: "Eternal boots", category: "armor", tier: "medium" },
  { id: 11832, name: "Bandos chestplate", category: "armor", tier: "medium" },
  { id: 11834, name: "Bandos tassets", category: "armor", tier: "medium" },
  { id: 11836, name: "Bandos boots", category: "armor", tier: "medium" },
  { id: 11828, name: "Armadyl chestplate", category: "armor", tier: "medium" },
  { id: 11830, name: "Armadyl chainskirt", category: "armor", tier: "medium" },
  { id: 19550, name: "Ring of suffering", category: "jewelry", tier: "medium" },
  { id: 19547, name: "Necklace of anguish", category: "jewelry", tier: "medium" },
  { id: 19553, name: "Amulet of torture", category: "jewelry", tier: "medium" },
  { id: 19544, name: "Tormented bracelet", category: "jewelry", tier: "low" },
  { id: 25975, name: "Lightbearer", category: "jewelry", tier: "low" },
  { id: 22477, name: "Avernic defender hilt", category: "shields", tier: "low" },
  { id: 11284, name: "Dragonfire shield", category: "shields", tier: "medium" },
  { id: 22003, name: "Dragonfire ward", category: "shields", tier: "medium" },
  { id: 23956, name: "Crystal armour seed", category: "herbs", tier: "low" },
  { id: 4207, name: "Crystal weapon seed", category: "herbs", tier: "low" },
  { id: 25859, name: "Enhanced crystal weapon seed", category: "herbs", tier: "low" },
  { id: 20997, name: "Twisted bow", category: "weapons", tier: "high" },
  { id: 22486, name: "Scythe of vitur (uncharged)", category: "weapons", tier: "high" },
  { id: 27277, name: "Tumeken's shadow (uncharged)", category: "weapons", tier: "high" },
  { id: 12817, name: "Elysian spirit shield", category: "herbs", tier: "high" },
  { id: 12825, name: "Arcane spirit shield", category: "herbs", tier: "high" },
  { id: 12821, name: "Spectral spirit shield", category: "herbs", tier: "low" },
  { id: 25985, name: "Elidinis' ward", category: "shields", tier: "low" },
  { id: 21000, name: "Twisted buckler", category: "shields", tier: "low" },
  { id: 21015, name: "Dinh's bulwark", category: "shields", tier: "low" },
  { id: 26374, name: "Zaryte crossbow", category: "weapons", tier: "high" },
  { id: 22978, name: "Dragon hunter lance", category: "weapons", tier: "medium" },
  { id: 22324, name: "Ghrazi rapier", category: "weapons", tier: "low" },
  { id: 22481, name: "Sanguinesti staff (uncharged)", category: "weapons", tier: "low" },
  { id: 21006, name: "Kodai wand", category: "weapons", tier: "high" },
  { id: 24422, name: "Nightmare staff", category: "weapons", tier: "low" },
  { id: 24511, name: "Harmonised orb", category: "resources", tier: "high" },
  { id: 24517, name: "Eldritch orb", category: "resources", tier: "high" },
  { id: 24514, name: "Volatile orb", category: "resources", tier: "high" },
  { id: 24417, name: "Inquisitor's mace", category: "weapons", tier: "high" },
  { id: 24419, name: "Inquisitor's great helm", category: "armor", tier: "high" },
  { id: 24420, name: "Inquisitor's hauberk", category: "armor", tier: "high" },
  { id: 24421, name: "Inquisitor's plateskirt", category: "other", tier: "high" },
  { id: 22326, name: "Justiciar faceguard", category: "armor", tier: "low" },
  { id: 22327, name: "Justiciar chestguard", category: "armor", tier: "low" },
  { id: 22328, name: "Justiciar legguards", category: "armor", tier: "low" },
  { id: 26382, name: "Torva full helm", category: "armor", tier: "high" },
  { id: 26384, name: "Torva platebody", category: "armor", tier: "high" },
  { id: 26386, name: "Torva platelegs", category: "armor", tier: "high" },
  { id: 27226, name: "Masori mask", category: "armor", tier: "high" },
  { id: 27229, name: "Masori body", category: "armor", tier: "high" },
  { id: 27232, name: "Masori chaps", category: "armor", tier: "high" },
  { id: 27235, name: "Masori mask (f)", category: "armor", tier: "high" },
  { id: 27238, name: "Masori body (f)", category: "armor", tier: "high" },
  { id: 27241, name: "Masori chaps (f)", category: "armor", tier: "high" },
  { id: 21018, name: "Ancestral hat", category: "armor", tier: "high" },
  { id: 21021, name: "Ancestral robe top", category: "armor", tier: "high" },
  { id: 21024, name: "Ancestral robe bottom", category: "armor", tier: "high" },
  { id: 26241, name: "Virtus mask", category: "armor", tier: "high" },
  { id: 26243, name: "Virtus robe top", category: "armor", tier: "high" },
  { id: 11804, name: "Bandos godsword", category: "weapons", tier: "medium" },
  { id: 11802, name: "Armadyl godsword", category: "weapons", tier: "medium" },
  { id: 11806, name: "Saradomin godsword", category: "weapons", tier: "low" },
  { id: 11808, name: "Zamorak godsword", category: "weapons", tier: "low" },
  { id: 13265, name: "Abyssal dagger", category: "weapons", tier: "low" },
  { id: 13263, name: "Abyssal bludgeon", category: "weapons", tier: "low" },
  { id: 27690, name: "Voidwaker", category: "other", tier: "low" },
  { id: 26233, name: "Ancient godsword", category: "weapons", tier: "low" },
  { id: 27662, name: "Accursed sceptre (u)", category: "weapons", tier: "low" },
  { id: 11920, name: "Dragon pickaxe", category: "weapons", tier: "medium" },
  { id: 6739, name: "Dragon axe", category: "weapons", tier: "medium" },
  { id: 20724, name: "Imbued heart", category: "upgrades", tier: "low" },
  { id: 21270, name: "Eternal gem", category: "upgrades", tier: "medium" },
  { id: 22966, name: "Hydra's claw", category: "upgrades", tier: "low" },
  { id: 21034, name: "Dexterous prayer scroll", category: "upgrades", tier: "low" },
  { id: 21079, name: "Arcane prayer scroll", category: "upgrades", tier: "high" }
];

export function getAllAnalysisItems() {
  return EXPANDED_ITEM_POOL.map(item => ({
    id: item.id,
    name: item.name
  }));
}

export function getItemsByCategory(category: ItemPoolEntry['category']) {
  return EXPANDED_ITEM_POOL.filter(item => item.category === category);
}

export function getItemsByTier(tier: ItemPoolEntry['tier']) {
  return EXPANDED_ITEM_POOL.filter(item => item.tier === tier);
}
