-- Stores raw OSRS Wiki /latest payloads for later scoring/reconciliation.
-- Keep it intentionally simple for MVP.

create table if not exists public.osrs_wiki_latest_ingests (
  id bigint generated by default as identity primary key,
  fetched_at timestamptz not null default now(),
  source text not null default 'prices.runescape.wiki/api/v1/osrs/latest',
  payload jsonb not null
);

create index if not exists osrs_wiki_latest_ingests_fetched_at_idx
  on public.osrs_wiki_latest_ingests (fetched_at desc);
